### ISSUE TITLE
500 Errors on homepage

### ISSUE THREAD

**Issue by janigowski** [aantipov/moiva-catalog#7]
![image](https://user-images.githubusercontent.com/8960952/102519794-3ba56f80-4093-11eb-8357-393db7726ca2.png)

**Comment by aantipov** [comment]
@dawidjaniga Thanks for reporting. I also noticed the problem. It was a problem with npm.io service which is used for autosuggestions.
Now the problem is gone.
I also added an error handling for such case to show an error message to the user.

I will monitor it. Gonna prepare a backup solution using npmjs service
